
CREATE ROLE productcatalogue LOGIN
  ENCRYPTED PASSWORD 'md5ce6b124a7067df660aa942393e50c6bd'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
  
CREATE DATABASE productcatalogue
  WITH OWNER = productcatalogue
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_GB.UTF-8'
       LC_CTYPE = 'en_GB.UTF-8'
       CONNECTION LIMIT = -1;