package dellstore.dao

import com.rits.orm.Entity
import com.rits.orm.IntId
import dellstore.model.Category
import com.rits.orm.ValuesMap
import com.rits.orm.Persisted
import com.rits.orm.utils.CRUD
import com.rits.orm.MapperDao
import com.rits.orm.utils.All
import com.rits.orm.QueryDao

/**
 * dao for the Category class
 *
 * @author kostantinos.kougios
 *
 * 30 Aug 2011
 */
class CategoryDao(val mapperDao: MapperDao, val queryDao: QueryDao) extends CRUD[IntId, Category, Int] with All[IntId, Category] {
	import CategoryDao._
	val entity = CategoryEntity
}

object CategoryDao {
	object CategoryEntity extends Entity[IntId, Category]("Categories", classOf[Category]) {
		val id = autoGeneratedPK("category", _.id)
		val name = string("categoryname", _.name)

		val constructor = (m: ValuesMap) => new Category(m(name)) with Persisted with IntId {
			val valuesMap = m
			val id = m(CategoryEntity.id)
		}
	}

}