package dellstore.dao
import com.rits.orm.Entity
import com.rits.orm.IntId
import dellstore.model._
import com.rits.orm.ValuesMap
import com.rits.orm.Persisted
import com.rits.orm.utils.CRUD
import com.rits.orm.utils.All
import com.rits.orm.MapperDao
import com.rits.orm.QueryDao
import com.rits.orm.utils.IntIdCRUD
import com.rits.orm.utils.IntIdAll
import com.rits.orm.SimpleEntity

/**
 * @author kostantinos.kougios
 *
 * 30 Aug 2011
 */
class ProductDao(val mapperDao: MapperDao, val queryDao: QueryDao) extends IntIdCRUD[Product] with IntIdAll[Product] {
	import ProductDao._
	val entity = ProductEntity
}

object ProductDao {
	object InventoryEntity extends SimpleEntity[Inventory]("inventory", classOf[Inventory]) {
		val stock = int("quan_in_stock", _.stock)
		val sales = int("sales", _.sales)
		val product = oneToOne(classOf[Product], "prod_id", _.product)
		val constructor = (m: ValuesMap) => new Inventory(m(product), m(stock), m(sales)) with Persisted {
			val valuesMap = m
		}
	}
	object ProductEntity extends Entity[IntId, Product]("products", classOf[Product]) {
		val id = autoGeneratedPK("prod_id", _.id)
		val title = string("title", _.title)
		val actor = string("actor", _.actor)
		val price = float("price", _.price)
		val category = manyToOne("category", classOf[Category], _.category)
		val special = boolean("special", _.special)
		val inventory = oneToOneReverse(classOf[Inventory], "prod_id", _.inventory)

		val constructor = (m: ValuesMap) => new Product(m(category), m(title), m(actor), m.float(price), m.boolean(special), m(inventory)) with Persisted with IntId {
			val valuesMap = m
			val id = m(ProductEntity.id)
		}
	}
}