package dellstore.dao
import com.rits.orm.Entity
import com.rits.orm.IntId
import dellstore.model.Product
import com.rits.orm.ValuesMap
import com.rits.orm.Persisted
import dellstore.model.Category
import com.rits.orm.utils.CRUD
import com.rits.orm.utils.All
import com.rits.orm.MapperDao
import com.rits.orm.QueryDao
import com.rits.orm.utils.IntIdCRUD
import com.rits.orm.utils.IntIdAll

/**
 * @author kostantinos.kougios
 *
 * 30 Aug 2011
 */
class ProductDao(val mapperDao: MapperDao, val queryDao: QueryDao) extends IntIdCRUD[Product] with IntIdAll[Product] {
	import ProductDao._
	val entity = ProductEntity
}

object ProductDao {
	object ProductEntity extends Entity[IntId, Product]("products", classOf[Product]) {
		val id = autoGeneratedPK("prod_id", _.id)
		val title = string("title", _.title)
		val actor = string("actor", _.actor)
		val category = manyToOne("category", classOf[Category], _.category)

		val constructor = (m: ValuesMap) => new Product(m(category), m(title), m(actor)) with Persisted with IntId {
			val valuesMap = m
			val id = m(ProductEntity.id)
		}
	}
}