package dellstore.dao

import com.googlecode.mapperdao._
import dellstore.model._

object CategoryEntity extends Entity[IntId, Category]("Categories") {
	val id = key("category") autogenerated (_.id)
	val name = column("categoryname") to (_.name)

	def constructor(implicit m) = new Category(name) with Persisted with IntId {
		val id: Int = CategoryEntity.id
	}
}
