package dellstore.dao
import com.googlecode.mapperdao.utils.IntIdAll
import com.googlecode.mapperdao.utils.IntIdCRUD
import com.googlecode.mapperdao.Entity
import com.googlecode.mapperdao.IntId
import com.googlecode.mapperdao.MapperDao
import com.googlecode.mapperdao.Persisted
import com.googlecode.mapperdao.Query
import com.googlecode.mapperdao.QueryDao
import com.googlecode.mapperdao.SimpleEntity
import com.googlecode.mapperdao.ValuesMap
import dellstore.model.Customer
import dellstore.model.Product
import dellstore.model.Order
import dellstore.model.OrderLine
import com.googlecode.mapperdao.utils.TransactionalIntIdCRUD

/**
 * @author kostantinos.kougios
 *
 * 1 Sep 2011
 */
abstract class OrderDao extends TransactionalIntIdCRUD[Order] with IntIdAll[Order] {
	import OrderDao._
	val entity = OrderEntity

	import Query._
	import queryDao._

	private val o = OrderEntity
	private val c = CustomerDao.CustomerEntity

	/**
	 * returns all orders from customers living at the provided state
	 */
	def byState(state: String): List[Order with IntId] = query(select from o join (o, o.customer, c) where c.state === state)
	/**
	 * all orders that the totalamount is between min and max
	 */
	def byTotal(min: Double, max: Double): List[Order with IntId] = query(select from o where o.totalAmount >= min and o.totalAmount <= max)
}

object OrderDao {
	object OrderEntity extends Entity[IntId, Order]("orders", classOf[Order]) {
		val orderid = intAutoGeneratedPK("orderid", _.id)
		val date = datetime("orderdate", _.date)
		val customer = manyToOne("customerid", classOf[Customer], _.customer)
		val netAmount = bigDecimal("netamount", _.netAmount)
		val tax = bigDecimal("tax", _.tax)
		val totalAmount = bigDecimal("totalamount", _.totalAmount)
		val orderLines = oneToMany(classOf[OrderLine], "orderid", _.orderLines)

		def constructor(implicit m: ValuesMap) = new Order(date, customer, netAmount, tax, totalAmount, orderLines) with Persisted with IntId {
			val id: Int = orderid
		}
	}

	object OrderLineEntity extends SimpleEntity[OrderLine]("orderlines", classOf[OrderLine]) {
		val orderlineid = intPK("orderlineid", _.id)
		val order = manyToOne("orderid", classOf[Order], _.order)
		val product = oneToOne(classOf[Product], "prod_id", _.product)
		val quantity = int("quantity", _.quantity)
		val orderdate = datetime("orderdate", _.date)

		def constructor(implicit m: ValuesMap) = new OrderLine(orderlineid, order, product, quantity, orderdate) with Persisted
	}
}