package dellstore.dao

import com.googlecode.mapperdao._
import dellstore.model.Order
import scala.annotation.target.getter

object OrderEntity extends Entity[IntId, Order]("orders") {
	val orderid = key("orderid") autogenerated (_.id)
	val date = column("orderdate") to (_.date)
	/**
	 * map CustomerEntity to orders.customerid . We also want to lazy load this entity
	 * and to do so we need to declare the getter Order.customer
	 */
	val customer = manytoone(CustomerEntity) foreignkey "customerid" getter "customer" to (_.customer)
	val netAmount = column("netamount") to (_.netAmount)
	val tax = column("tax") to (_.tax)
	val totalAmount = column("totalamount") to (_.totalAmount)
	/**
	 * An order can have many order lines. orderlines.orderid is the foreign key for this relationship and
	 * we do the mapping here.
	 *
	 * We also want to lazy load this entity
	 * and to do so we need to declare the getter Order.orderLines
	 */
	val orderLines = onetomany(OrderLineEntity) foreignkey "orderid" getter "orderLines" to (_.orderLines)

	def constructor(implicit m) = new Order(date, customer, netAmount, tax, totalAmount, orderLines) with Persisted with IntId {
		val id: Int = orderid
	}
}
