package dellstore.dao

import com.googlecode.mapperdao._
import dellstore.model.Order

object OrderEntity extends Entity[IntId, Order]("orders") {
	val orderid = key("orderid") autogenerated (_.id)
	val date = column("orderdate") to (_.date)
	val customer = manytoone(CustomerEntity) foreignkey "customerid" to (_.customer)
	val netAmount = column("netamount") to (_.netAmount)
	val tax = column("tax") to (_.tax)
	val totalAmount = column("totalamount") to (_.totalAmount)
	val orderLines = onetomany(OrderLineEntity) foreignkey "orderid" to (_.orderLines)

	def constructor(implicit m) = new Order(date, customer, netAmount, tax, totalAmount, orderLines) with Persisted with IntId {
		val id: Int = orderid
	}
}
